// <auto-generated />
using CSVReaderAPI.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSVReaderAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("CSVReaderAPI.Models.Data.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address1_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_country")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_postalcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_street1")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_street2")
                        .HasColumnType("TEXT");

                    b.Property<string>("business_phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("company_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_type")
                        .HasColumnType("TEXT");

                    b.Property<string>("department")
                        .HasColumnType("TEXT");

                    b.Property<string>("emailaddress1")
                        .HasColumnType("TEXT");

                    b.Property<string>("first_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("job_title")
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
